# Generated by Django 3.0.6 on 2020-12-09 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(max_length=1000)),
                ('measurement_type', models.CharField(choices=[('ml', 'ml'), ('l', 'l'), ('fl_oz', 'fl oz'), ('pt', 'pint'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('oz', 'oz'), ('mg', 'mg'), ('g', 'g'), ('lb', 'lb')], default='g', max_length=100)),
                ('method', models.TextField(max_length=2000)),
                ('course', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('side', 'Sides')], max_length=50)),
                ('time', models.TimeField()),
                ('servings', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
