# Generated by Django 3.0.6 on 2020-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipeexternalwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeexternalwebsite',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='recipe_image/'),
        ),
    ]
